version: '3.9'

services:
  db_auth:
    container_name: db_auth
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:15.5-alpine3.18
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db: